build-settings: &build-settings
  working_directory: /usr/src/SlicerExecutionModel

version: 2
jobs:
  itk-v4.8.0_use_system_libraries-off:
    <<: *build-settings
    docker:
      - image: hjmjohnson/slicerexecutionmodel:${CIRCLE_JOB}
    steps:
      - checkout
      - run:
          command: ./test/Docker/test.sh ${CIRCLE_JOB}

  # ITK v4.10.1
  itk-v4.10.1_use_system_libraries-off:
    <<: *build-settings
    docker:
      - image: hjmjohnson/slicerexecutionmodel:${CIRCLE_JOB}
    steps:
      - checkout
      - run:
          command: ./test/Docker/test.sh ${CIRCLE_JOB}
      - run:
          command: ./test/Docker/test-serializer.sh ${CIRCLE_JOB}

  # ITK v4.13.0
  itk-v4.13.0_use_system_libraries-off:
    <<: *build-settings
    docker:
      - image: hjmjohnson/slicerexecutionmodel:${CIRCLE_JOB}
    steps:
      - checkout
      - run:
          command: ./test/Docker/test.sh ${CIRCLE_JOB}
      - run:
          command: ./test/Docker/test-serializer.sh ${CIRCLE_JOB}


  # ITK master
  itk-master_use_system_libraries-off:
    <<: *build-settings
    docker:
      - image: hjmjohnson/slicerexecutionmodel:${CIRCLE_JOB}
    steps:
      - checkout
      - run:
          command: ./test/Docker/test.sh ${CIRCLE_JOB}
      - run:
          command: ./test/Docker/test-serializer.sh ${CIRCLE_JOB}

workflows:
  version: 2
  build-test:
    jobs:
      - itk-v4.8.0_use_system_libraries-off
      - itk-v4.10.1_use_system_libraries-off
      - itk-v4.13.0_use_system_libraries-off
      - itk-master_use_system_libraries-off
