name: CI (Build)

on:
  # Triggers the workflow on push or pull request events
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_tag: [itk-master_use_system_libraries-off]
    container:
      image: slicer/slicerexecutionmodel:${{ matrix.image_tag}}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Test"
        run: ./test/Docker/test.sh ${{ matrix.image_tag}}

      - name: "Test Serializer"
        run: ./test/Docker/test-serializer.sh ${{ matrix.image_tag}}
